<?php

declare(strict_types=1);

/*
 * (c) 2020 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use AppBundle\Entity\Source;
use Doctrine\ORM\EntityRepository;

/**
 * ClippingRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClippingRepository extends EntityRepository {
    public function searchQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->addSelect('MATCH (e.transcription) AGAINST (:q BOOLEAN) AS HIDDEN score');
        $qb->andWhere('MATCH (e.transcription) AGAINST(:q BOOLEAN) > 0.0');
        $qb->orderBy('score', 'desc');
        $qb->setParameter('q', $q);

        return $qb->getQuery();
    }

    public function categoryQuery(Category $category) {
        $qb = $this->createQueryBuilder('e');
        $qb->andWhere('e.category = :category');
        $qb->setParameter('category', $category);
        $qb->orderBy('e.id');

        return $qb->getQuery();
    }

    public function sourceQuery(Source $source) {
        $qb = $this->createQueryBuilder('e');
        $qb->andWhere('e.source = :source');
        $qb->setParameter('source', $source);
        $qb->orderBy('e.id');

        return $qb->getQuery();
    }
}
