<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\Category;
use App\Entity\Clipping;
use App\Entity\Source;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ClippingRepository.
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClippingRepository extends ServiceEntityRepository {
    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, Clipping::class);
    }

    private function fulltextPart(QueryBuilder $qb, array $data, string $fieldName, string $formName) : void {
        if ( ! isset($data[$formName])) {
            return;
        }
        $term = trim($data[$formName]);
        if ( ! $term) {
            return;
        }

        $m = [];
        if (preg_match('/^"(.*)"$/u', $term, $m)) {
            $qb->andWhere("e.{$fieldName} like :{$fieldName}Exact");
            $qb->setParameter("{$fieldName}Exact", "%{$m[1]}%");
        } else {
            $qb->andWhere("MATCH (e.{$fieldName}) AGAINST(:{$fieldName} BOOLEAN) > 0");
            $qb->setParameter($fieldName, $term);
        }
    }

    private function textPart(QueryBuilder $qb, array $data, string $fieldName, string $formName) : void {
        if ( ! isset($data[$formName])) {
            return;
        }
        $term = trim($data[$formName]);
        if ( ! $term) {
            return;
        }
        $qb->andWhere("e.{$fieldName} like :{$fieldName}");
        $qb->setParameter("{$fieldName}", "%{$term}%");
    }

    private function arrayPart(QueryBuilder $qb, array $data, string $fieldName, string $formName) : void {
        if ( ! isset($data[$formName])) {
            return;
        }

        /** @var Collection $list */
        $list = $data[$formName];
        if ( ! count($list)) {
            return;
        }
        $qb->andWhere("e.{$fieldName} IN (:{$fieldName})");
        $qb->setParameter($fieldName, $list->toArray());
    }

    public function searchQuery(array $data) : Query {
        $qb = $this->createQueryBuilder('e');
        $this->fulltextPart($qb, $data, 'transcription', 'transcription');

        if (isset($data['number']) && $data['number']) {
            $term = trim($data['number']);
            $qb->andWhere('e.number like :number');
            $qb->setParameter('number', "{$term}%");
        }

        $this->textPart($qb, $data, 'writtenDate', 'writtenDate');
        $this->textPart($qb, $data, 'date', 'date');

        $this->arrayPart($qb, $data, 'category', 'category');
        $this->arrayPart($qb, $data, 'source', 'source');

        if (isset($data['order']) && $data['order']) {
            switch ($data['order']) {
                case 'date':
                    $qb->orderBy('e.date', 'ASC');

                    break;

                case 'number':
                    $qb->orderBy('CONVERT(e.number, integer)');
                    $qb->addOrderBy('e.number', 'ASC');

                    break;

                default:
            }
        }

        return $qb->getQuery();
    }

    public function categoryQuery(Category $category) : Query {
        $qb = $this->createQueryBuilder('e');
        $qb->addSelect('CAST(e.number as integer) HIDDEN n');
        $qb->andWhere('e.category = :category');
        $qb->setParameter('category', $category);
        $qb->orderBy('n', 'ASC');
        $qb->addOrderBy('e.date', 'ASC');
        $qb->addOrderBy('e.id', 'ASC');

        return $qb->getQuery();
    }

    public function sourceQuery(Source $source) : Query {
        $qb = $this->createQueryBuilder('e');
        $qb->addSelect('CAST(e.number as integer) HIDDEN n');
        $qb->andWhere('e.source = :source');
        $qb->setParameter('source', $source);
        $qb->orderBy('n', 'ASC');
        $qb->addOrderBy('e.date', 'ASC');
        $qb->addOrderBy('e.id', 'ASC');

        return $qb->getQuery();
    }
}
